"""Typed contracts exported for adapters and application consumers."""

from curupira.models.azure import (
    AzHref,
    AzPullRequest,
    AzPullRequestLinks,
    AzPullRequestSearchRequest,
    AzurePullRequestStatus,
)
from curupira.models.configuration import (
    AgentDefaults,
    AgentsSettings,
    AssistantSettings,
    AutomationConfiguration,
    AzurePullRequestAutomationConfiguration,
    CodingAgentDefaults,
    CodingAgentsSettings,
    CronAutomationConfiguration,
    ExecutionSettings,
    IssueAutomationConfiguration,
    PollingSettings,
    PullRequestAutomationConfiguration,
    RepositoryConfiguration,
    TrelloAutomationConfiguration,
)
from curupira.models.github import (
    DEFAULT_ISSUE_JSON_FIELDS,
    GhIssue,
    GhIssueReference,
    GhLabel,
    GhPullRequest,
    GhRepositoryReference,
    GhStatusCheck,
    GhTaskViewRequest,
    GitHubSearchRequest,
)
from curupira.models.items import CronItem, IssueItem, PullRequestItem, TrelloCardItem
from curupira.models.process import (
    CodingTaskRequest,
    CommandRequest,
    DispatchOutcome,
    ProcessResult,
)
from curupira.models.profiles import (
    ClaudeCodeCliProfile,
    CliProfile,
    CliProfileBase,
    CodexCliProfile,
    CursorCliProfile,
    OpenCodeCliProfile,
)
from curupira.models.tasks import (
    CompletedTaskState,
    CronRunState,
    ResolvedAutomation,
    RunningCodingSession,
    Task,
    TaskIdentity,
    WorkflowStage,
)
from curupira.models.templates import common_prompt_context, flatten_for_template
from curupira.models.trello import TrelloBoard, TrelloCard, TrelloList, TrelloListRequest

__all__ = [
    "DEFAULT_ISSUE_JSON_FIELDS",
    "AgentDefaults",
    "AgentsSettings",
    "AssistantSettings",
    "AutomationConfiguration",
    "AzHref",
    "AzPullRequest",
    "AzPullRequestLinks",
    "AzPullRequestSearchRequest",
    "AzurePullRequestAutomationConfiguration",
    "AzurePullRequestStatus",
    "ClaudeCodeCliProfile",
    "CliProfile",
    "CliProfileBase",
    "CodexCliProfile",
    "CodingAgentDefaults",
    "CodingAgentsSettings",
    "CodingTaskRequest",
    "CommandRequest",
    "CompletedTaskState",
    "CronAutomationConfiguration",
    "CronItem",
    "CronRunState",
    "CursorCliProfile",
    "DispatchOutcome",
    "ExecutionSettings",
    "GhIssue",
    "GhIssueReference",
    "GhLabel",
    "GhPullRequest",
    "GhRepositoryReference",
    "GhStatusCheck",
    "GhTaskViewRequest",
    "GitHubSearchRequest",
    "IssueAutomationConfiguration",
    "IssueItem",
    "OpenCodeCliProfile",
    "PollingSettings",
    "ProcessResult",
    "PullRequestAutomationConfiguration",
    "PullRequestItem",
    "RepositoryConfiguration",
    "ResolvedAutomation",
    "RunningCodingSession",
    "Task",
    "TaskIdentity",
    "TrelloAutomationConfiguration",
    "TrelloBoard",
    "TrelloCard",
    "TrelloCardItem",
    "TrelloList",
    "TrelloListRequest",
    "WorkflowStage",
    "common_prompt_context",
    "flatten_for_template",
]
